//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REISys.Training.Repository.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int EmployeeId { get; set; }
        public int AddressId { get; set; }
        public string PhoneNumber { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
